[workspace]
members = [
    "redeem-openms-ffi",
    "redeem-classifiers",
    "redeem-cli",
    "redeem-properties",
    "redeem-properties-py",
]

resolver = "2"

[patch.crates-io]
redeem-properties = { path = "redeem-properties" }
candle-core = { git = "https://github.com/singjc/candle.git", branch = "add/candle-onnx-export" }
candle-nn = { git = "https://github.com/singjc/candle.git", branch = "add/candle-onnx-export" }
candle-transformers = { git = "https://github.com/singjc/candle.git", branch = "add/candle-onnx-export" }

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
debug = true

[profile.openms-ffi-release]
inherits = "release"
lto = false
codegen-units = 16
debug = false
strip = "debuginfo"
