[workspace]
members = [
    "redeem-openms-ffi",
    "redeem-classifiers",
    "redeem-cli",
    "redeem-properties",
    "redeem-properties-py",
]

resolver = "2"

[patch.crates-io]
redeem-properties = { path = "redeem-properties" }

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
debug = true
